/*
 * Servers.com OpenAPI Specification
 *
 * # Authentication We use bearerAuth with JSON Web Tokens for Authentication. You must send this token in the Authorization header when making requests to protected resources: ``` Authorization: Bearer <JWTtoken> ```  You can find more information [here](https://swagger.io/docs/specification/authentication/bearer-authentication/)   # Pagination We use [github style pagination](https://developer.github.com/v3/#pagination) with [WebLinking](https://tools.ietf.org/html/rfc5988). Maximum 100 results per page.  # Rate limits 2000 requests per account per hour. You can see your limits in the following response headers * `X-RateLimit-Limit`  for a total limit * `X-RateLimit-Remaining` for remaining limit * `X-RateLimit-Reset` for timestamp when the oldest request will expire 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
import (
	"time"
)
// TheItemsSchema1 struct for TheItemsSchema1
type TheItemsSchema1 struct {
	Id string `json:"id,omitempty"`
	Number int32 `json:"number,omitempty"`
	Hostname string `json:"hostname,omitempty"`
	Configuration string `json:"configuration,omitempty"`
	Type string `json:"type,omitempty"`
	Role string `json:"role,omitempty"`
	Status string `json:"status,omitempty"`
	PrivateIpv4Address string `json:"private_ipv4_address,omitempty"`
	PublicIpv4Address string `json:"public_ipv4_address,omitempty"`
	RefId string `json:"ref_id,omitempty"`
	ClusterId string `json:"cluster_id,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
