/*
 * Servers.com OpenAPI Specification
 *
 * # Authentication We use bearerAuth with JSON Web Tokens for Authentication. You must send this token in the Authorization header when making requests to protected resources: ``` Authorization: Bearer <JWTtoken> ```  You can find more information [here](https://swagger.io/docs/specification/authentication/bearer-authentication/)   # Pagination We use [github style pagination](https://developer.github.com/v3/#pagination) with [WebLinking](https://tools.ietf.org/html/rfc5988). Maximum 100 results per page.  # Rate limits 2000 requests per account per hour. You can see your limits in the following response headers * `X-RateLimit-Limit`  for a total limit * `X-RateLimit-Remaining` for remaining limit * `X-RateLimit-Reset` for timestamp when the oldest request will expire 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// InlineObject struct for InlineObject
type InlineObject struct {
	//  location
	LocationId int32 `json:"location_id"`
	//  server model
	ServerModelId int32 `json:"server_model_id"`
	UplinkModels V1HostsDedicatedServersUplinkModels `json:"uplink_models"`
	//  ram size
	RamSize int32 `json:"ram_size"`
	Drives V1HostsDedicatedServersDrives `json:"drives"`
	//  features
	Features []string `json:"features,omitempty"`
	//  ipv6
	Ipv6 bool `json:"ipv6,omitempty"`
	//  hosts
	Hosts []V1HostsDedicatedServersHosts `json:"hosts"`
	//  operation system
	OperationSystemId int32 `json:"operation_system_id,omitempty"`
	//  ssh key fingerprints
	SshKeyFingerprints []string `json:"ssh_key_fingerprints,omitempty"`
}
