/*
 * Servers.com OpenAPI Specification
 *
 * # Authentication We use bearerAuth with JSON Web Tokens for Authentication. You must send this token in the Authorization header when making requests to protected resources: ``` Authorization: Bearer <JWTtoken> ```  You can find more information [here](https://swagger.io/docs/specification/authentication/bearer-authentication/)   # Pagination We use [github style pagination](https://developer.github.com/v3/#pagination) with [WebLinking](https://tools.ietf.org/html/rfc5988). Maximum 100 results per page.  # Rate limits 2000 requests per account per hour. You can see your limits in the following response headers * `X-RateLimit-Limit`  for a total limit * `X-RateLimit-Remaining` for remaining limit * `X-RateLimit-Reset` for timestamp when the oldest request will expire
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// InlineObject8 struct for InlineObject8
type InlineObject8 struct {
	//  name
	Name string `json:"name,omitempty"`
	//  healthcheck url
	HealthcheckUrl string `json:"healthcheck_url,omitempty"`
	//  redirect http
	RedirectHttp bool `json:"redirect_http,omitempty"`
	//  geoip enabled
	GeoipEnabled bool `json:"geoip_enabled,omitempty"`
	//  rules
	Rules []V1LoadBalancersL7IdRules `json:"rules,omitempty"`
}
